// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: pb/dog/dog.proto

package dog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *DogReq) Reset() {
	*x = DogReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_dog_dog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogReq) ProtoMessage() {}

func (x *DogReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dog_dog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogReq.ProtoReflect.Descriptor instead.
func (*DogReq) Descriptor() ([]byte, []int) {
	return file_pb_dog_dog_proto_rawDescGZIP(), []int{0}
}

func (x *DogReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DogReq) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type DogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *DogResp) Reset() {
	*x = DogResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_dog_dog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DogResp) ProtoMessage() {}

func (x *DogResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dog_dog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DogResp.ProtoReflect.Descriptor instead.
func (*DogResp) Descriptor() ([]byte, []int) {
	return file_pb_dog_dog_proto_rawDescGZIP(), []int{1}
}

func (x *DogResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DogResp) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

var File_pb_dog_dog_proto protoreflect.FileDescriptor

var file_pb_dog_dog_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x62, 0x2f, 0x64, 0x6f, 0x67, 0x2f, 0x64, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x64, 0x6f, 0x67, 0x22, 0x2e, 0x0a, 0x06, 0x44, 0x6f, 0x67, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x07, 0x44, 0x6f, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x32, 0xb2, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x0b, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x65,
	0x71, 0x1a, 0x0c, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x27, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6e, 0x12, 0x0b, 0x2e, 0x64, 0x6f,
	0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44,
	0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x12, 0x28, 0x0a, 0x09, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x4f, 0x75, 0x74, 0x12, 0x0b, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x30, 0x01, 0x12, 0x29, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x4f, 0x12, 0x0b,
	0x2e, 0x64, 0x6f, 0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x64, 0x6f,
	0x67, 0x2e, 0x44, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1b, 0x5a,
	0x19, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x6d, 0x79, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x64, 0x6f, 0x67, 0x3b, 0x64, 0x6f, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pb_dog_dog_proto_rawDescOnce sync.Once
	file_pb_dog_dog_proto_rawDescData = file_pb_dog_dog_proto_rawDesc
)

func file_pb_dog_dog_proto_rawDescGZIP() []byte {
	file_pb_dog_dog_proto_rawDescOnce.Do(func() {
		file_pb_dog_dog_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_dog_dog_proto_rawDescData)
	})
	return file_pb_dog_dog_proto_rawDescData
}

var file_pb_dog_dog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_dog_dog_proto_goTypes = []interface{}{
	(*DogReq)(nil),  // 0: dog.DogReq
	(*DogResp)(nil), // 1: dog.DogResp
}
var file_pb_dog_dog_proto_depIdxs = []int32{
	0, // 0: dog.SearchService.Search:input_type -> dog.DogReq
	0, // 1: dog.SearchService.SearchIn:input_type -> dog.DogReq
	0, // 2: dog.SearchService.SearchOut:input_type -> dog.DogReq
	0, // 3: dog.SearchService.SearchIO:input_type -> dog.DogReq
	1, // 4: dog.SearchService.Search:output_type -> dog.DogResp
	1, // 5: dog.SearchService.SearchIn:output_type -> dog.DogResp
	1, // 6: dog.SearchService.SearchOut:output_type -> dog.DogResp
	1, // 7: dog.SearchService.SearchIO:output_type -> dog.DogResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_dog_dog_proto_init() }
func file_pb_dog_dog_proto_init() {
	if File_pb_dog_dog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_dog_dog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DogReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_dog_dog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DogResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_dog_dog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_dog_dog_proto_goTypes,
		DependencyIndexes: file_pb_dog_dog_proto_depIdxs,
		MessageInfos:      file_pb_dog_dog_proto_msgTypes,
	}.Build()
	File_pb_dog_dog_proto = out.File
	file_pb_dog_dog_proto_rawDesc = nil
	file_pb_dog_dog_proto_goTypes = nil
	file_pb_dog_dog_proto_depIdxs = nil
}
